//! BN-style tag system: categorised address / function annotations
//! that sit alongside the existing CommentManager.
//!
//! Comments are free-form text. Tags add a *category* so a user can
//! ask "show me every Crypto finding" or "list the Suspicious
//! functions" without grep-style guessing. BN ships a built-in
//! taxonomy (`Bugs`, `Crashes`, `Important`, `Library`, `Crypto`, …)
//! plus a user-creatable type registry; we mirror the built-in set
//! and let the analyzer pipeline register new types on demand.
//!
//! Two scopes:
//!
//! * **Address tags** — attached to a specific instruction or data
//!   byte. e.g. `crypto: AES S-box` at the `.rodata` slot.
//! * **Function tags** — attached to a function entry address.
//!   e.g. `important: hot function` at every fan-in-rich entry.
//!
//! Each tag carries:
//!   - `kind` — the TagKind (canonical category)
//!   - `text` — the analyzer-supplied detail string
//!   - `auto` — true when an analyzer added it (regenerated each
//!     analysis run, not persisted to overrides); false when the
//!     user added it via override sidecar
//!
//! Tags are *separate from* CommentManager — analyzers usually emit
//! both: a free-form comment for the listing, and a tag for the
//! categorised report. The duplicated text is a feature: the
//! comment annotates the byte stream, the tag drives filterable
//! reports.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// Built-in tag categories. Matches the BN starter set + a few we
/// emit elsewhere in the pipeline. Custom kinds use `Custom(String)`
/// so plugins / overrides can introduce their own without changing
/// this enum.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum TagKind {
    Important,
    Suspicious,
    Library,
    Crypto,
    Bug,
    Crash,
    NoReturn,
    Wrapper,
    Recursive,
    Loop,
    StackProtected,
    AntiDebug,
    Exception,
    Custom(String),
}

impl TagKind {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Important => "important",
            Self::Suspicious => "suspicious",
            Self::Library => "library",
            Self::Crypto => "crypto",
            Self::Bug => "bug",
            Self::Crash => "crash",
            Self::NoReturn => "noreturn",
            Self::Wrapper => "wrapper",
            Self::Recursive => "recursive",
            Self::Loop => "loop",
            Self::StackProtected => "stack_protected",
            Self::AntiDebug => "anti_debug",
            Self::Exception => "exception",
            Self::Custom(s) => s.as_str(),
        }
    }

    /// Parse a category slug into a `TagKind`. Not implementing
    /// `std::str::FromStr` because the conversion is infallible —
    /// unknown strings fall into `Custom(_)` — and `FromStr`'s
    /// `Err` machinery would force callers through a needless
    /// `Result` wrapper.
    pub fn parse(s: &str) -> Self {
        match s {
            "important" => Self::Important,
            "suspicious" => Self::Suspicious,
            "library" => Self::Library,
            "crypto" => Self::Crypto,
            "bug" => Self::Bug,
            "crash" => Self::Crash,
            "noreturn" => Self::NoReturn,
            "wrapper" => Self::Wrapper,
            "recursive" => Self::Recursive,
            "loop" => Self::Loop,
            "stack_protected" => Self::StackProtected,
            "anti_debug" => Self::AntiDebug,
            "exception" => Self::Exception,
            other => Self::Custom(other.to_string()),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tag {
    pub kind: TagKind,
    pub text: String,
    /// `true` when generated by an analyzer (re-derived on each run);
    /// `false` when the user added it via override sidecar.
    pub auto: bool,
}

#[derive(Debug, Default)]
pub struct TagManager {
    /// Address-scope tags: (address, [tags]).
    by_address: BTreeMap<u64, Vec<Tag>>,
    /// Function-scope tags: (function_entry, [tags]).
    by_function: BTreeMap<u64, Vec<Tag>>,
}

impl TagManager {
    pub fn new() -> Self {
        Self::default()
    }

    /// Tag an address. The same `(address, kind)` pair is allowed to
    /// appear multiple times — different analyzers may add the same
    /// kind for different reasons (e.g. crypto: AES S-box + crypto:
    /// MD5 init), and we keep both.
    pub fn add_address(&mut self, address: u64, kind: TagKind, text: impl Into<String>, auto: bool) {
        self.by_address.entry(address).or_default().push(Tag {
            kind,
            text: text.into(),
            auto,
        });
    }

    pub fn add_function(&mut self, entry: u64, kind: TagKind, text: impl Into<String>, auto: bool) {
        self.by_function.entry(entry).or_default().push(Tag {
            kind,
            text: text.into(),
            auto,
        });
    }

    pub fn address_tags(&self, address: u64) -> &[Tag] {
        self.by_address.get(&address).map(Vec::as_slice).unwrap_or(&[])
    }

    pub fn function_tags(&self, entry: u64) -> &[Tag] {
        self.by_function.get(&entry).map(Vec::as_slice).unwrap_or(&[])
    }

    /// Iterate every (address, &Tag) pair. Helpful for `tags` CLI
    /// command and JSON export.
    pub fn iter_addresses(&self) -> impl Iterator<Item = (u64, &Tag)> {
        self.by_address
            .iter()
            .flat_map(|(addr, tags)| tags.iter().map(move |t| (*addr, t)))
    }

    pub fn iter_functions(&self) -> impl Iterator<Item = (u64, &Tag)> {
        self.by_function
            .iter()
            .flat_map(|(addr, tags)| tags.iter().map(move |t| (*addr, t)))
    }

    /// Filter address tags by kind. Avoids forcing callers to walk
    /// the full iterator when they only want a single category.
    pub fn addresses_of_kind<'a>(&'a self, kind: &'a TagKind) -> impl Iterator<Item = (u64, &'a Tag)> {
        self.iter_addresses().filter(move |(_, t)| &t.kind == kind)
    }

    pub fn functions_of_kind<'a>(&'a self, kind: &'a TagKind) -> impl Iterator<Item = (u64, &'a Tag)> {
        self.iter_functions().filter(move |(_, t)| &t.kind == kind)
    }

    /// Total counts grouped by kind, across both scopes. Used by the
    /// `summary` CLI and the `tags --list-types` report.
    pub fn counts_by_kind(&self) -> BTreeMap<String, usize> {
        let mut out: BTreeMap<String, usize> = BTreeMap::new();
        for (_, t) in self.iter_addresses() {
            *out.entry(t.kind.as_str().to_string()).or_insert(0) += 1;
        }
        for (_, t) in self.iter_functions() {
            *out.entry(t.kind.as_str().to_string()).or_insert(0) += 1;
        }
        out
    }

    pub fn len(&self) -> usize {
        self.by_address.values().map(Vec::len).sum::<usize>()
            + self.by_function.values().map(Vec::len).sum::<usize>()
    }

    pub fn is_empty(&self) -> bool {
        self.by_address.is_empty() && self.by_function.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn add_and_query() {
        let mut mgr = TagManager::new();
        mgr.add_address(0x1000, TagKind::Crypto, "AES S-box", true);
        mgr.add_function(0x2000, TagKind::Important, "hot function", true);
        assert_eq!(mgr.address_tags(0x1000).len(), 1);
        assert_eq!(mgr.function_tags(0x2000).len(), 1);
        assert_eq!(mgr.len(), 2);
    }

    #[test]
    fn filter_by_kind() {
        let mut mgr = TagManager::new();
        mgr.add_address(0x1000, TagKind::Crypto, "a", true);
        mgr.add_address(0x2000, TagKind::Suspicious, "b", true);
        mgr.add_address(0x3000, TagKind::Crypto, "c", true);
        let cryptos: Vec<_> = mgr.addresses_of_kind(&TagKind::Crypto).collect();
        assert_eq!(cryptos.len(), 2);
    }

    #[test]
    fn counts_by_kind() {
        let mut mgr = TagManager::new();
        mgr.add_address(0x1000, TagKind::Crypto, "a", true);
        mgr.add_function(0x2000, TagKind::Crypto, "b", true);
        mgr.add_function(0x3000, TagKind::Important, "c", true);
        let counts = mgr.counts_by_kind();
        assert_eq!(counts.get("crypto"), Some(&2));
        assert_eq!(counts.get("important"), Some(&1));
    }

    #[test]
    fn custom_kind_roundtrip() {
        let k = TagKind::parse("my-custom-thing");
        assert_eq!(k.as_str(), "my-custom-thing");
        assert!(matches!(k, TagKind::Custom(_)));
    }

    #[test]
    fn known_kind_roundtrip() {
        for s in [
            "important", "suspicious", "library", "crypto", "bug",
            "noreturn", "wrapper", "recursive", "loop",
            "stack_protected", "anti_debug", "exception",
        ] {
            assert_eq!(TagKind::parse(s).as_str(), s);
        }
    }
}
