//! MIPS32 → P-code lifter.
//!
//! MIPS has a regular fixed-width (4-byte) encoding, so P-code is generated by
//! decoding instruction fields directly; capstone is used only for the
//! human-readable disassembly text. Covers the common integer ALU, load/store,
//! and branch/jump instructions.
//!
//! Note: MIPS branch *delay slots* are not reordered — each instruction's
//! P-code is emitted at its own address. Data-flow for ALU ops is exact;
//! consumers that care about precise delay-slot timing should account for this.

use gr_core::address::{Address, Endian, SpaceId};
use gr_core::pcode::{OpCode, PcodeOp, SeqNum, VarnodeData};
use gr_loader::Memory;
use smallvec::SmallVec;

use crate::lift::{LiftError, LiftedInstruction, PcodeLift};

const CONST_SPACE: SpaceId = SpaceId::CONST;
const RAM_SPACE: SpaceId = SpaceId::RAM;
const REG_SPACE: SpaceId = SpaceId::REGISTER;
const UNIQUE_SPACE: SpaceId = SpaceId::UNIQUE;

const RA_INDEX: u32 = 31; // $ra

fn constant(value: u64, size: u32) -> VarnodeData {
    VarnodeData::new(CONST_SPACE, value, size)
}

fn ram(addr: u64) -> VarnodeData {
    VarnodeData::new(RAM_SPACE, addr, 4)
}

fn unique(offset: u64, size: u32) -> VarnodeData {
    VarnodeData::new(UNIQUE_SPACE, offset, size)
}

/// Source operand for register `n`: the zero register reads as constant 0.
fn reg_in(n: u32) -> VarnodeData {
    if n == 0 {
        constant(0, 4)
    } else {
        VarnodeData::new(REG_SPACE, n as u64 * 4, 4)
    }
}

/// Destination operand for register `n`: writes to the zero register are
/// discarded (returns `None`).
fn reg_out(n: u32) -> Option<VarnodeData> {
    if n == 0 {
        None
    } else {
        Some(VarnodeData::new(REG_SPACE, n as u64 * 4, 4))
    }
}

fn lo_reg() -> VarnodeData {
    VarnodeData::new(REG_SPACE, 34 * 4, 4)
}

fn hi_reg() -> VarnodeData {
    VarnodeData::new(REG_SPACE, 33 * 4, 4)
}

pub struct MipsLifter {
    cs: capstone::Capstone,
    big_endian: bool,
}

// Capstone's C library is thread-safe for independent instances.
unsafe impl Send for MipsLifter {}
unsafe impl Sync for MipsLifter {}

impl MipsLifter {
    pub fn new_32(endian: Endian) -> Self {
        use capstone::prelude::*;
        let cs_endian = match endian {
            Endian::Big => capstone::Endian::Big,
            Endian::Little => capstone::Endian::Little,
        };
        let cs = Capstone::new_raw(
            capstone::Arch::MIPS,
            arch::mips::ArchMode::Mips32.into(),
            std::iter::empty(),
            Some(cs_endian),
        )
        .expect("failed to create MIPS capstone");
        Self {
            cs,
            big_endian: matches!(endian, Endian::Big),
        }
    }

    fn read_word(&self, buf: &[u8; 4]) -> u32 {
        if self.big_endian {
            u32::from_be_bytes(*buf)
        } else {
            u32::from_le_bytes(*buf)
        }
    }

    /// Decode one 32-bit MIPS word at `address` into P-code ops.
    fn lift_word(&self, word: u32, address: u64) -> Vec<PcodeOp> {
        let seq = |order: u32| SeqNum::new(Address::new(RAM_SPACE, address), order);
        let mut ops: Vec<PcodeOp> = Vec::new();
        let mut s: u32 = 0;

        let opcode = (word >> 26) & 0x3F;
        let rs = (word >> 21) & 0x1F;
        let rt = (word >> 16) & 0x1F;
        let rd = (word >> 11) & 0x1F;
        let shamt = (word >> 6) & 0x1F;
        let funct = word & 0x3F;
        let imm16 = word & 0xFFFF;
        let sext_imm = imm16 as i16 as i64 as u64; // sign-extended to 64 then masked on use
        let target26 = word & 0x03FF_FFFF;

        let next = address + 4;
        let branch_target = next.wrapping_add(((imm16 as i16 as i64) << 2) as u64);
        let jump_target = (next & 0xF000_0000) | ((target26 as u64) << 2);

        // Helper to push a simple binary ALU op writing rd.
        let binop_rd = |ops: &mut Vec<PcodeOp>, s: &mut u32, op: OpCode, a: VarnodeData, b: VarnodeData| {
            if let Some(out) = reg_out(rd) {
                ops.push(PcodeOp {
                    opcode: op,
                    seq: seq(*s),
                    output: Some(out),
                    inputs: SmallVec::from_slice(&[a, b]),
                });
                *s += 1;
            }
        };

        match opcode {
            0x00 => {
                // SPECIAL — dispatch on funct
                match funct {
                    0x20 | 0x21 => binop_rd(&mut ops, &mut s, OpCode::IntAdd, reg_in(rs), reg_in(rt)), // add/addu
                    0x22 | 0x23 => binop_rd(&mut ops, &mut s, OpCode::IntSub, reg_in(rs), reg_in(rt)), // sub/subu
                    0x24 => binop_rd(&mut ops, &mut s, OpCode::IntAnd, reg_in(rs), reg_in(rt)),        // and
                    0x25 => binop_rd(&mut ops, &mut s, OpCode::IntOr, reg_in(rs), reg_in(rt)),         // or
                    0x26 => binop_rd(&mut ops, &mut s, OpCode::IntXor, reg_in(rs), reg_in(rt)),        // xor
                    0x27 => {
                        // nor rd = ~(rs | rt)
                        if let Some(out) = reg_out(rd) {
                            let tmp = unique(0x100, 4);
                            ops.push(PcodeOp { opcode: OpCode::IntOr, seq: seq(s), output: Some(tmp), inputs: SmallVec::from_slice(&[reg_in(rs), reg_in(rt)]) });
                            s += 1;
                            ops.push(PcodeOp { opcode: OpCode::IntNegate, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[tmp]) });
                            s += 1;
                        }
                    }
                    0x2A => binop_rd(&mut ops, &mut s, OpCode::IntSLess, reg_in(rs), reg_in(rt)), // slt
                    0x2B => binop_rd(&mut ops, &mut s, OpCode::IntLess, reg_in(rs), reg_in(rt)),  // sltu
                    0x00 => binop_rd(&mut ops, &mut s, OpCode::IntLeft, reg_in(rt), constant(shamt as u64, 4)),  // sll
                    0x02 => binop_rd(&mut ops, &mut s, OpCode::IntRight, reg_in(rt), constant(shamt as u64, 4)), // srl
                    0x03 => binop_rd(&mut ops, &mut s, OpCode::IntSRight, reg_in(rt), constant(shamt as u64, 4)),// sra
                    0x04 => binop_rd(&mut ops, &mut s, OpCode::IntLeft, reg_in(rt), reg_in(rs)),  // sllv
                    0x06 => binop_rd(&mut ops, &mut s, OpCode::IntRight, reg_in(rt), reg_in(rs)), // srlv
                    0x07 => binop_rd(&mut ops, &mut s, OpCode::IntSRight, reg_in(rt), reg_in(rs)),// srav
                    0x08 => {
                        // jr rs
                        if rs == RA_INDEX {
                            ops.push(PcodeOp { opcode: OpCode::Return, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[reg_in(rs)]) });
                        } else {
                            ops.push(PcodeOp { opcode: OpCode::BranchInd, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[reg_in(rs)]) });
                        }
                    }
                    0x09 => {
                        // jalr rs (link defaults to $ra)
                        ops.push(PcodeOp { opcode: OpCode::CallInd, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[reg_in(rs)]) });
                    }
                    0x18 | 0x19 => {
                        // mult/multu — low product into lo (hi ignored)
                        ops.push(PcodeOp { opcode: OpCode::IntMult, seq: seq(s), output: Some(lo_reg()), inputs: SmallVec::from_slice(&[reg_in(rs), reg_in(rt)]) });
                    }
                    0x1A => {
                        // div — lo = rs/rt, hi = rs%rt (signed)
                        ops.push(PcodeOp { opcode: OpCode::IntSDiv, seq: seq(s), output: Some(lo_reg()), inputs: SmallVec::from_slice(&[reg_in(rs), reg_in(rt)]) });
                        s += 1;
                        ops.push(PcodeOp { opcode: OpCode::IntSRem, seq: seq(s), output: Some(hi_reg()), inputs: SmallVec::from_slice(&[reg_in(rs), reg_in(rt)]) });
                    }
                    0x1B => {
                        // divu
                        ops.push(PcodeOp { opcode: OpCode::IntDiv, seq: seq(s), output: Some(lo_reg()), inputs: SmallVec::from_slice(&[reg_in(rs), reg_in(rt)]) });
                        s += 1;
                        ops.push(PcodeOp { opcode: OpCode::IntRem, seq: seq(s), output: Some(hi_reg()), inputs: SmallVec::from_slice(&[reg_in(rs), reg_in(rt)]) });
                    }
                    _ => {}
                }
            }
            0x01 => {
                // REGIMM — rt field selects condition (bltz=0, bgez=1)
                let cond = unique(0x200, 1);
                let (op, a, b) = if rt == 0 {
                    (OpCode::IntSLess, reg_in(rs), constant(0, 4)) // bltz: rs < 0
                } else {
                    (OpCode::IntSLessEqual, constant(0, 4), reg_in(rs)) // bgez: 0 <= rs
                };
                ops.push(PcodeOp { opcode: op, seq: seq(s), output: Some(cond), inputs: SmallVec::from_slice(&[a, b]) });
                s += 1;
                ops.push(PcodeOp { opcode: OpCode::CBranch, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[ram(branch_target), cond]) });
            }
            0x02 => {
                // j target
                ops.push(PcodeOp { opcode: OpCode::Branch, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[ram(jump_target)]) });
            }
            0x03 => {
                // jal target
                ops.push(PcodeOp { opcode: OpCode::Call, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[ram(jump_target)]) });
            }
            0x04 | 0x05 => {
                // beq / bne
                let cond = unique(0x200, 1);
                let op = if opcode == 0x04 { OpCode::IntEqual } else { OpCode::IntNotEqual };
                ops.push(PcodeOp { opcode: op, seq: seq(s), output: Some(cond), inputs: SmallVec::from_slice(&[reg_in(rs), reg_in(rt)]) });
                s += 1;
                ops.push(PcodeOp { opcode: OpCode::CBranch, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[ram(branch_target), cond]) });
            }
            0x06 => {
                // blez: rs <= 0 (signed)
                let cond = unique(0x200, 1);
                ops.push(PcodeOp { opcode: OpCode::IntSLessEqual, seq: seq(s), output: Some(cond), inputs: SmallVec::from_slice(&[reg_in(rs), constant(0, 4)]) });
                s += 1;
                ops.push(PcodeOp { opcode: OpCode::CBranch, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[ram(branch_target), cond]) });
            }
            0x07 => {
                // bgtz: rs > 0 (signed)  ==  0 < rs
                let cond = unique(0x200, 1);
                ops.push(PcodeOp { opcode: OpCode::IntSLess, seq: seq(s), output: Some(cond), inputs: SmallVec::from_slice(&[constant(0, 4), reg_in(rs)]) });
                s += 1;
                ops.push(PcodeOp { opcode: OpCode::CBranch, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[ram(branch_target), cond]) });
            }
            0x08 | 0x09 => {
                // addi / addiu  rt = rs + sext(imm)
                if let Some(out) = reg_out(rt) {
                    ops.push(PcodeOp { opcode: OpCode::IntAdd, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[reg_in(rs), constant(sext_imm & 0xFFFF_FFFF, 4)]) });
                }
            }
            0x0A => {
                // slti rt = (rs < sext(imm)) signed
                if let Some(out) = reg_out(rt) {
                    ops.push(PcodeOp { opcode: OpCode::IntSLess, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[reg_in(rs), constant(sext_imm & 0xFFFF_FFFF, 4)]) });
                }
            }
            0x0B => {
                // sltiu rt = (rs < sext(imm)) unsigned
                if let Some(out) = reg_out(rt) {
                    ops.push(PcodeOp { opcode: OpCode::IntLess, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[reg_in(rs), constant(sext_imm & 0xFFFF_FFFF, 4)]) });
                }
            }
            0x0C => {
                // andi rt = rs & zext(imm)
                if let Some(out) = reg_out(rt) {
                    ops.push(PcodeOp { opcode: OpCode::IntAnd, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[reg_in(rs), constant(imm16 as u64, 4)]) });
                }
            }
            0x0D => {
                // ori rt = rs | zext(imm)
                if let Some(out) = reg_out(rt) {
                    ops.push(PcodeOp { opcode: OpCode::IntOr, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[reg_in(rs), constant(imm16 as u64, 4)]) });
                }
            }
            0x0E => {
                // xori rt = rs ^ zext(imm)
                if let Some(out) = reg_out(rt) {
                    ops.push(PcodeOp { opcode: OpCode::IntXor, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[reg_in(rs), constant(imm16 as u64, 4)]) });
                }
            }
            0x0F => {
                // lui rt = imm << 16
                if let Some(out) = reg_out(rt) {
                    ops.push(PcodeOp { opcode: OpCode::Copy, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[constant((imm16 as u64) << 16, 4)]) });
                }
            }
            0x20 | 0x21 | 0x23 | 0x24 | 0x25 => {
                // lb / lh / lw / lbu / lhu
                let (load_size, signed) = match opcode {
                    0x20 => (1, true),  // lb
                    0x21 => (2, true),  // lh
                    0x24 => (1, false), // lbu
                    0x25 => (2, false), // lhu
                    _ => (4, false),    // lw
                };
                if let Some(out) = reg_out(rt) {
                    let addr = unique(0x300, 4);
                    ops.push(PcodeOp { opcode: OpCode::IntAdd, seq: seq(s), output: Some(addr), inputs: SmallVec::from_slice(&[reg_in(rs), constant(sext_imm & 0xFFFF_FFFF, 4)]) });
                    s += 1;
                    if load_size == 4 {
                        ops.push(PcodeOp { opcode: OpCode::Load, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[constant(RAM_SPACE.0 as u64, 4), addr]) });
                    } else {
                        let loaded = unique(0x310, load_size);
                        ops.push(PcodeOp { opcode: OpCode::Load, seq: seq(s), output: Some(loaded), inputs: SmallVec::from_slice(&[constant(RAM_SPACE.0 as u64, 4), addr]) });
                        s += 1;
                        let ext = if signed { OpCode::IntSExt } else { OpCode::IntZExt };
                        ops.push(PcodeOp { opcode: ext, seq: seq(s), output: Some(out), inputs: SmallVec::from_slice(&[loaded]) });
                    }
                }
            }
            0x28 | 0x29 | 0x2B => {
                // sb / sh / sw
                let store_size = match opcode {
                    0x28 => 1, // sb
                    0x29 => 2, // sh
                    _ => 4,    // sw
                };
                let addr = unique(0x300, 4);
                ops.push(PcodeOp { opcode: OpCode::IntAdd, seq: seq(s), output: Some(addr), inputs: SmallVec::from_slice(&[reg_in(rs), constant(sext_imm & 0xFFFF_FFFF, 4)]) });
                s += 1;
                // Value: low `store_size` bytes of rt (register file is little-endian internally).
                let value = if rt == 0 {
                    constant(0, store_size)
                } else {
                    VarnodeData::new(REG_SPACE, rt as u64 * 4, store_size)
                };
                ops.push(PcodeOp { opcode: OpCode::Store, seq: seq(s), output: None, inputs: SmallVec::from_slice(&[constant(RAM_SPACE.0 as u64, 4), addr, value]) });
            }
            _ => {}
        }

        let _ = s;
        ops
    }
}

impl PcodeLift for MipsLifter {
    fn lift_instruction(&self, memory: &Memory, address: u64) -> Result<LiftedInstruction, LiftError> {
        let mut buf = [0u8; 4];
        memory
            .read_bytes(address, &mut buf)
            .map_err(|_| LiftError::UnreadableAddress(address))?;

        let word = self.read_word(&buf);
        let ops = self.lift_word(word, address);

        // Disassembly text from capstone (best effort).
        let mnemonic = match self.cs.disasm_count(&buf, address, 1) {
            Ok(insns) => insns
                .iter()
                .next()
                .map(|insn| {
                    let m = insn.mnemonic().unwrap_or("???");
                    let o = insn.op_str().unwrap_or("");
                    if o.is_empty() { m.to_string() } else { format!("{} {}", m, o) }
                })
                .unwrap_or_else(|| format!(".word 0x{:08x}", word)),
            Err(_) => format!(".word 0x{:08x}", word),
        };

        Ok(LiftedInstruction { address, length: 4, mnemonic, ops })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gr_core::address::SpaceId as CoreSpace;
    use gr_loader::memory::{MemoryBlock, MemoryFlags};
    use std::sync::Arc;

    fn make_memory(words: &[u32], addr: u64, big_endian: bool) -> Memory {
        let mut bytes = Vec::new();
        for w in words {
            if big_endian {
                bytes.extend_from_slice(&w.to_be_bytes());
            } else {
                bytes.extend_from_slice(&w.to_le_bytes());
            }
        }
        let mut mem = Memory::new(CoreSpace(1), if big_endian { Endian::Big } else { Endian::Little });
        mem.add_block(MemoryBlock {
            name: ".text".into(),
            start: addr,
            size: bytes.len() as u64,
            flags: MemoryFlags::READ | MemoryFlags::EXECUTE,
            data: Some(Arc::from(bytes.as_slice())),
        });
        mem
    }

    #[test]
    fn lift_nop() {
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[0x0000_0000], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert!(lifted.ops.is_empty(), "nop should produce no ops");
        assert_eq!(lifted.length, 4);
    }

    #[test]
    fn lift_addu() {
        // addu $a0, $a1, $a2  => op=0 rs=5 rt=6 rd=4 funct=0x21
        let word = (5 << 21) | (6 << 16) | (4 << 11) | 0x21;
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[word], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert_eq!(lifted.ops.len(), 1);
        assert_eq!(lifted.ops[0].opcode, OpCode::IntAdd);
        // output is $a0 = reg 4 => offset 16
        assert_eq!(lifted.ops[0].output.unwrap().offset, 16);
    }

    #[test]
    fn lift_addiu() {
        // addiu $a0, $a1, 16 => op=9 rs=5 rt=4 imm=16
        let word = (0x09 << 26) | (5 << 21) | (4 << 16) | 16;
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[word], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert_eq!(lifted.ops.len(), 1);
        assert_eq!(lifted.ops[0].opcode, OpCode::IntAdd);
        let imm = &lifted.ops[0].inputs[1];
        assert_eq!(imm.space, CoreSpace::CONST);
        assert_eq!(imm.offset, 16);
    }

    #[test]
    fn lift_lw() {
        // lw $a0, 0($sp) => op=0x23 rs=29 rt=4 imm=0
        let word = (0x23 << 26) | (29 << 21) | (4 << 16);
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[word], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        // address compute + load
        assert!(lifted.ops.iter().any(|o| o.opcode == OpCode::Load));
        assert!(lifted.ops.iter().any(|o| o.opcode == OpCode::IntAdd));
    }

    #[test]
    fn lift_sw() {
        // sw $a0, 4($sp) => op=0x2B rs=29 rt=4 imm=4
        let word = (0x2B << 26) | (29 << 21) | (4 << 16) | 4;
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[word], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert!(lifted.ops.iter().any(|o| o.opcode == OpCode::Store));
    }

    #[test]
    fn lift_jr_ra_is_return() {
        // jr $ra => op=0 rs=31 funct=8
        let word = (31 << 21) | 0x08;
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[word], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert_eq!(lifted.ops.len(), 1);
        assert_eq!(lifted.ops[0].opcode, OpCode::Return);
    }

    #[test]
    fn lift_beq() {
        // beq $a0, $a1, +8 => op=4 rs=4 rt=5 imm=2 (2 words)
        let word = (0x04 << 26) | (4 << 21) | (5 << 16) | 2;
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[word], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert!(lifted.ops.iter().any(|o| o.opcode == OpCode::IntEqual));
        let cbr = lifted.ops.iter().find(|o| o.opcode == OpCode::CBranch).unwrap();
        // target = next(0x1004) + (2 << 2) = 0x100C
        assert_eq!(cbr.inputs[0].offset, 0x100C);
    }

    #[test]
    fn lift_j() {
        // j 0x400 => op=2 target=0x100 (word index) => addr (0x100 << 2)=0x400
        let word = (0x02 << 26) | 0x100;
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[word], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert_eq!(lifted.ops[0].opcode, OpCode::Branch);
        assert_eq!(lifted.ops[0].inputs[0].offset, 0x400);
    }

    #[test]
    fn write_to_zero_register_discarded() {
        // addu $zero, $a1, $a2 => writing $0 produces no op
        let word = (5 << 21) | (6 << 16) | 0x21; // rd=0
        let lifter = MipsLifter::new_32(Endian::Big);
        let mem = make_memory(&[word], 0x1000, true);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert!(lifted.ops.is_empty());
    }

    #[test]
    fn little_endian_decode() {
        // addu $a0, $a1, $a2 in little-endian memory
        let word = (5 << 21) | (6 << 16) | (4 << 11) | 0x21;
        let lifter = MipsLifter::new_32(Endian::Little);
        let mem = make_memory(&[word], 0x1000, false);
        let lifted = lifter.lift_instruction(&mem, 0x1000).unwrap();
        assert_eq!(lifted.ops[0].opcode, OpCode::IntAdd);
    }
}
