pub mod action;
pub mod cast;
pub mod cfg;
pub mod comments_gen;
pub mod dataflow;
pub mod dominator;
pub mod emit;
pub mod rust_emit;
pub mod optimize;
pub mod pipeline;
pub mod printer;
pub mod scope;
pub mod ssa;
pub mod structure;
pub mod taint;
pub mod token;
pub mod typeinfer;
pub mod varrecovery;

pub use pipeline::{analyze_taint, decompile, decompile_all, decompile_function, DecompileResult, DecompileStats, TaintReport};
pub use taint::{TaintEngine, TaintSink, TaintSinkKind};
pub use token::{Token, TokenDocument, TokenLine, TokenType};
pub use typeinfer::{InferredType, TypeInferenceEngine};
