pub mod breakpoint;
pub mod debugger;
pub mod emulator;
pub mod gdbserver;
pub mod hooks;
pub mod memory_model;
pub mod network;
pub mod process;
pub mod session;
pub mod snapshot;
pub mod state;
pub mod syscall;
pub mod tui;
pub mod watchpoint;
pub mod trace;

pub use breakpoint::{BreakCondition, Breakpoint, BreakpointManager};
pub use emulator::Emulator;
pub use gdbserver::{DebugTarget, GdbStub, StopReason};
pub use state::EmulatorState;
pub use tui::{parse_debug_command, DebugCommand};
pub use trace::{MemoryProtection, PagePermissions, TraceLog, TraceRecord};
