pub mod action;
pub mod callee_params;
pub mod callers;
pub mod cast;
pub mod cfg;
pub mod condition;
pub mod comments_gen;
pub mod dataflow;
pub mod dominator;
pub mod emit;
pub mod flags;
pub mod rust_emit;
pub mod noreturn;
pub mod optimize;
pub mod pipeline;
pub mod printer;
pub mod scope;
pub mod semantic_diff;
pub mod ssa;
pub mod structure;
pub mod taint;
pub mod token;
pub mod typeinfer;
pub mod varrecovery;
pub mod vcall;

pub use pipeline::{analyze_taint, decompile, decompile_all, decompile_function, DecompileResult, DecompileStats, TaintReport};
pub use semantic_diff::{compare_programs, structural_hash, exact_hash, FunctionDiff, FunctionDiffKind};
pub use taint::{TaintEngine, TaintSink, TaintSinkKind};
pub use token::{Token, TokenDocument, TokenLine, TokenType};
pub use typeinfer::{InferredType, TypeInferenceEngine};
