pub mod analyzer;
#[cfg(test)]
mod testutil;
pub mod addrtable;
pub mod boundary;
pub mod callingconv;
pub mod callgraph;
pub mod callsite;
pub mod coverage;
pub mod dataref;
pub mod demangle;
pub mod discovery;
pub mod ehframe;
pub mod filler;
pub mod indirect;
pub mod iterate;
pub mod manager;
pub mod propagation;
pub mod references;
pub mod stack;
pub mod strings;
pub mod switches;
pub mod noreturn_prop;
pub mod patterns;
pub mod pcoderef;
pub mod rtti;
pub mod signatures;
pub mod thunk;
pub mod typerecovery;
pub mod utils;
pub mod vtable;
pub mod xref_report;

pub use analyzer::Analyzer;
pub use callgraph::CallGraph;
pub use manager::AnalysisManager;
