//! Detect wrapper functions: a function whose entire body is
//! `[prologue?] call other_func; [epilogue?]`.
//!
//! These are everywhere in real binaries:
//!
//! * C++ vtable thunks (`virtual void X::foo() → call Base::foo()`)
//! * PLT-bypass forwarders generated by `--wrap=symbol`
//! * Compiler "shrink-wrapped" alternate entry points
//! * Manual `__attribute__((alias))` aliases
//! * Wide-char / narrow-char API pairs that delegate to a common
//!   implementation
//!
//! Knowing a function is "just a wrapper for X" makes IDA / Binary
//! Ninja transparently chase through them in callgraph view and
//! xref reports — we want the same. For each detected wrapper we:
//!
//! 1. Set a plate comment naming the delegate:
//!    `wrapper → printf`
//! 2. Record the relationship in metadata as
//!    `wrapper_<addr>_target = "<callee_name>"`.
//!
//! Detection rule (conservative):
//!
//! * The function has *exactly one* `call_target`.
//! * Its body contains 1..=8 instructions (typical wrapper size —
//!   prologue + call + epilogue).
//! * It contains at least one direct call instruction; the function
//!   must not just consist of a single jmp (that's a thunk and
//!   `ThunkDetectorAnalyzer` already handles it).
//!
//! This is intentionally narrower than IDA's "is this just a shim?"
//! heuristic — the goal is high precision over high recall. Anything
//! more complex (e.g. wrappers that recover from the callee's error
//! return) needs proper dataflow and is out of scope.

use std::collections::BTreeSet;

use gr_arch::FlowType;
use gr_program::comments::CommentType;
use gr_program::Program;

use crate::analyzer::{AnalysisError, AnalysisResult, Analyzer};

pub struct WrapperFunctionAnalyzer;

impl Analyzer for WrapperFunctionAnalyzer {
    fn name(&self) -> &str {
        "Wrapper Function"
    }
    fn description(&self) -> &str {
        "Flags functions that are minimal wrappers around exactly one delegate call"
    }
    fn priority(&self) -> u32 {
        // After CallSiteAnnotator / Signatures so the delegate name
        // we print is the best-resolved version.
        795
    }
    fn analyze(&self, program: &mut Program) -> Result<AnalysisResult, AnalysisError> {
        struct FuncSnap {
            entry: u64,
            ranges: Vec<(u64, u64)>,
            call_targets: BTreeSet<u64>,
            is_thunk: bool,
        }
        let snaps: Vec<FuncSnap> = program
            .listing
            .functions()
            .map(|f| FuncSnap {
                entry: f.entry_point,
                ranges: f
                    .body
                    .ranges()
                    .map(|r| (r.start.offset, r.start.offset + r.size))
                    .collect(),
                call_targets: f.call_targets.clone(),
                is_thunk: f.is_thunk,
            })
            .collect();

        let name_at = |program: &Program, addr: u64| -> Option<String> {
            program
                .symbol_table
                .primary_at(addr)
                .map(|s| s.name.clone())
                .or_else(|| program.listing.get_function(addr).map(|f| f.name.clone()))
        };

        let mut flagged: Vec<(u64, String)> = Vec::new();
        for snap in &snaps {
            if snap.is_thunk {
                continue;
            }
            if snap.call_targets.len() != 1 {
                continue;
            }

            let mut insn_count = 0usize;
            let mut has_call = false;
            for (s, e) in &snap.ranges {
                for ins in program.listing.instructions_in_range(*s, *e) {
                    insn_count += 1;
                    if matches!(ins.flow_type, FlowType::Call | FlowType::IndirectCall) {
                        has_call = true;
                    }
                }
            }
            // 1..=18 covers debug-build wrappers (`-O0` adds a
            // prologue + per-arg save/reload pattern that pushes
            // insn count up to ~15 even for `return f(args)` with
            // 3 args + endbr64 + leave/ret). Release builds with
            // full optimisation stay well under the cap.
            if !(1..=18).contains(&insn_count) || !has_call {
                continue;
            }

            let target = *snap.call_targets.iter().next().unwrap();
            let Some(target_name) = name_at(program, target) else {
                continue;
            };
            flagged.push((snap.entry, target_name));
        }

        let mut emitted = 0usize;
        for (entry, target_name) in &flagged {
            program.metadata.set_property(
                format!("wrapper_{:x}_target", entry),
                target_name.clone(),
            );
            if program.comments.get(*entry, CommentType::Plate).is_some() {
                continue;
            }
            program.comments.set(
                *entry,
                CommentType::Plate,
                format!("wrapper → {}", target_name),
            );
            emitted += 1;
        }

        Ok(AnalysisResult {
            analyzer_name: self.name().into(),
            functions_found: flagged.len(),
            references_found: 0,
            instructions_decoded: emitted,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn module_compiles() {
        let _ = WrapperFunctionAnalyzer;
    }
}
